import streamlit as st

st.write("""
# Persewaan Alat Outdoor""")
st.subheader("Berikut adalah daftar barang yang disewakan beserta gambarnya")
st.image('tenda_2_orang2-removebg-preview.png')
st.subheader("Tenda 2 Orang")
st.write(" Tenda 2 orang adalah tenda yang bisa memuat 2 orang, kami menyediakan tenda dengan kualitas yang baik,kami memiliki berbagai merek Naturehike, Malcone tent, Eiger")
st.image('tenda_4_orang-removebg-preview.png')
st.subheader("Tenda 4 Orang")
st.write(" Tenda 4 orang adalah tenda yang bisa memuat 4 orang, kami menyediakan tenda dengan kualitas yang baik kami memiliki berbagai merek Naturehike, Malcone tent, Eiger")
st.image('tenda_6_orang-removebg-preview.png')
st.subheader("Tenda 6 Orang")
st.write(" Tenda 6 orang adalah tenda yang bisa memuat 6 orang, kami menyediakan tenda dengan kualitas yang baik kami memiliki berbagai merek Naturehike, Malcone tent, Eiger")
st.image('matras-removebg-preview.png')
st.subheader("Matras")
st.write(" Matras digunakan sebagai alas untuk melindungi anda agar tidak kotor, matras mencegah suhu dingin dari tanah naik ke atas. Istirahat Anda saat camping jadi lebih nyaman dengan matras. Kami menyediakan produk yang bervariasi. Ada matras angin yang tebal hingga matras busa yang empuk. Kami memiliki berbagai merek seperti Eiger dan Naturehike")
st.image('kompor_portable-removebg-preview.png')
st.subheader("Kompor Portable")
st.write(" Kompor Portable untuk memasak dengan menggunakan gas berupa tabung kecil. Sangat cocok untuk membantu ada dalam kegiatan seperti naik gunung atau untuk memasak darurat saat tidak ada gas LPG. Kami menyediakan berbagai merek seperti Miyako, Cosmos, Winn Gas, dan juga Oxone.")
st.image('Sleeping_Bag-removebg-preview.png')
st.subheader("Sleeping Bag")
st.write(" Sleeping bag atau kantung tidur adalah alat yang digunakan sebagai alas tidur saat melakukan aktivitas outdoor. Sleeping bag yang berkualitas dapat menjaga suhu tubuh sehingga kamu bisa beristirahat dengan nyaman meski di alam terbuka. Kami menyediakan berbagai merek seperti Eiger, Polar Bulu, Highrock, Hammock, dan Onsight")
st.image('tas_carrier-removebg-preview.png')
st.subheader("Tas Carrier")
st.write(" Tas Carrier adalah benda paling penting bagi seorang pendaki. Tas punggung ini tidak sama dengan ransel karena memiliki kapasitas yang luas sehingga bisa memuat banyak barang untuk dibawa selama pendakian. Kami menyediakan Forester, Rei, Co-Trex, dan Eiger ")
st.image('nesting1-removebg-preview.png')
st.subheader("Nesting")
st.write(" Nesting camping adalah peralatan outdoor yang digunakan untuk mengolah bahan makanan alias peralatan memasak. Kami menyediakan berbagai merek seperti Firemaple dan Eiger")
st.image('flysheett-removebg-preview.png')
st.subheader("Flysheet")
st.write(" Flysheet adalah lapisan Polyester yang tahan air sehingga bisa melindungi dari hujan, terik matahari, angin juga debu. Kami menyediakan berbagai merek seperti Bogaboo dan Eiger")
st.image('headlamp-removebg-preview.png')
st.subheader("Headlamp")
st.write(" Headlamp adalah lampu yang dipasang di atas kepala untuk menerangi jalan di depan. Kami menyediakan berbagai merek seperti Nitecore, Alonefire dan Jetbeam")
st.image('sepatu1-removebg-preview.png')
st.subheader("Sepatu")
st.write(" Sepatu camping adalah hal penting untuk anda gunakan dalam kegiatan outdoor.Kerangka model sepatu gunung ini memberikan kenyamanan untuk kaki Anda melewati jalur pendakian. Kami menyediakan berbagai merek seperti Eiger dan Consina")
st.image('gasss-removebg-preview.png')
st.subheader("Gas Portable")
st.write(" Gas Portable merupakan bahan bakar yang sangat cocok untuk kebutuhan kegiatan mobile atau outdoor. Kami menyediakan berbagai merek seperti pertamina dan Winn gass")
st.image('senter-removebg-preview.png')
st.subheader("Senter")
st.write(" Senter digunakan untuk menerangi jalan dengan sorot jauh maupun dekat dengan pencahayaan membantu anda. Kami menyediakan berbagai merek seperti Police,Tent Ligh,Mitsuyama MS-4022")
